id: I47A76387
legacy_id: P006701
ocr_import_info:
  bdrc_scan_id: W30396
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T13:20:08'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:36:08.092356+00:00'
last_modified: 2022-09-03 19:36:15.835071
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30396
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW30396
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམ་ཚིག་ཐམས་ཅད་ཉམས་ཆགས་སྐོང་བའི་ལུང་བཤགས་པ་ཐམས་ཅད་ཀྱི་རྒྱུད་དྲི་མ་མེད་པའི་རྒྱལ་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.6922766848813283
  ocr_word_median_confidence_index: 0.8600000143051147
quality: null
bases:
  I6102:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6102
      total_pages: 196
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I6102.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.6922766848813283
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
